name: Reinforcement
version: '${project.version}'
main: com.person98.reinforcement.Reinforcement
depend: [DecentHolograms]
author: Person98
description: A plugin that allows you to reinforce blocks
commands:
  reinforce:
    description: Reinforce a block
    usage: /<command>